version: '3.8'

# ============================================
# Stack simplificado SIN Traefik
# Para testing con IP directa (sin HTTPS)
# ============================================

services:
  # ============================================
  # BACKEND - FastAPI
  # ============================================
  backend:
    image: ${REGISTRY_URL}lizicular-backend:${VERSION}
    
    # EXPONER PUERTO DIRECTAMENTE (sin Traefik)
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 20 && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --workers 4"
    
    environment:
      # Database connections
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/authdb
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      
      # App config
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      
      # URLs para testing con IP
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      
      # Cookie config (secure must be false for HTTP)
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=False

      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
    
    networks:
      - lizicular_network
    
    depends_on:
      - db
      - redis
      - mongodb
    
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================
  # FRONTEND - Next.js
  # ============================================
  frontend:
    image: ${REGISTRY_URL}lizicular-frontend:${VERSION}
    
    # EXPONER PUERTO DIRECTAMENTE (sin Traefik)
    ports:
      - "80:3000"
    
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL} # Public URL for the browser
      - INTERNAL_BACKEND_URL=http://backend:8000   # Internal Docker network URL for the server
      - BACKEND_URL=http://backend:8000
      - PORT=3000
    
    networks:
      - lizicular_network
    
    depends_on:
      - backend
    
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    # healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s

  # ============================================
  # POSTGRESQL
  # ============================================
  db:
    image: postgres:15-alpine
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=authdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Si tienes scripts de inicialización:
      # - ./backend/database/postgres-init:/docker-entrypoint-initdb.d:ro
    
    networks:
      - lizicular_network
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d authdb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ============================================
  # REDIS
  # ============================================
  redis:
    image: redis:7-alpine
    
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    
    volumes:
      - redis_data:/data
    
    networks:
      - lizicular_network
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cache == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ============================================
  # MONGODB
  # ============================================
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    
    command: >
      mongod
      --bind_ip_all
      --auth
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    
    networks:
      - lizicular_network
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      restart_policy:
        condition: any
        delay: 10s
      
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    healthcheck:
      test: |
        mongosh --eval "db.adminCommand('ping')" \
          -u ${MONGO_INITDB_ROOT_USERNAME} \
          -p ${MONGO_INITDB_ROOT_PASSWORD} \
          --authenticationDatabase admin --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ============================================
# NETWORKS
# ============================================
networks:
  lizicular_network:
    driver: overlay
    attachable: true

# ============================================
# VOLUMES
# ============================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
